export let CreatedWindow = false;

export class Villager2Loads {
    transactionText = "<div id='window'>" +
        "<div class=\"modal\" id=\"modal\" value=\"" + TransactionItems + "\">\n" +
        "    <div id='windowheader'>" +
        "<div class=\"title\">\n" +
        "        <p class=\"important\">请输入数据</p>\n" +
        "    </div>" +
        "</div>\n" +
        "    <div class=\"content\">\n" +
        "        <div id=\"msg\">\n" +
        "            <div id=\"com\" style=\"margin-top: 0 !important\">\n" +
        "                <label>\n" +
        "                    <p>最大购买数量（不填默认为1）</p>\n" +
        "                    <input id=\"max\" type=\"number\">\n" +
        "                    <p>买入的物品：</p>\n" +
        "                    <select id=\"buy\">\n" +
        "                        <option>铁剑</option>\n" +
        "                        <option>铁锹</option>\n" +
        "                        <option>铁镐</option>\n" +
        "                        <option>铁斧</option>\n" +
        "                        <option>铁锄</option>\n" +
        "                        <option>木剑</option>\n" +
        "                        <option>木锹</option>\n" +
        "                        <option>木镐</option>\n" +
        "                        <option>木斧</option>\n" +
        "                        <option>木锄</option>\n" +
        "                        <option>石剑</option>\n" +
        "                        <option>石锹</option>\n" +
        "                        <option>石镐</option>\n" +
        "                        <option>石斧</option>\n" +
        "                        <option>石锄</option>\n" +
        "                        <option>钻石剑</option>\n" +
        "                        <option>钻石锹</option>\n" +
        "                        <option>钻石镐</option>\n" +
        "                        <option>钻石斧</option>\n" +
        "                        <option>钻石锄</option>\n" +
        "                        <option>金剑</option>\n" +
        "                        <option>金锹</option>\n" +
        "                        <option>金镐</option>\n" +
        "                        <option>金斧</option>\n" +
        "                        <option>金锄</option>\n" +
        "                        <option>皮革头盔</option>\n" +
        "                        <option>皮革胸甲</option>\n" +
        "                        <option>皮革护腿</option>\n" +
        "                        <option>皮革靴子</option>\n" +
        "                        <option>锁链头盔</option>\n" +
        "                        <option>锁链胸甲</option>\n" +
        "                        <option>锁链护腿</option>\n" +
        "                        <option>锁链靴子</option>\n" +
        "                        <option>铁头盔</option>\n" +
        "                        <option>铁胸甲</option>\n" +
        "                        <option>铁护腿</option>\n" +
        "                        <option>铁靴子</option>\n" +
        "                        <option>钻石头盔</option>\n" +
        "                        <option>钻石胸甲</option>\n" +
        "                        <option>钻石护腿</option>\n" +
        "                        <option>钻石靴子</option>\n" +
        "                        <option>金头盔</option>\n" +
        "                        <option>金胸甲</option>\n" +
        "                        <option>金护腿</option>\n" +
        "                        <option>金靴子</option>\n" +
        "                        <option>海龟壳</option>\n" +
        "                        <option>鳞甲</option>\n" +
        "                        <option>打火石</option>\n" +
        "                        <option>弓</option>\n" +
        "                        <option>箭</option>\n" +
        "                        <option>苹果</option>\n" +
        "                        <option>煤炭</option>\n" +
        "                        <option>木炭</option>\n" +
        "                        <option>钻石</option>\n" +
        "                        <option>铁锭</option>\n" +
        "                        <option>金锭</option>\n" +
        "                        <option>木棍</option>\n" +
        "                        <option>碗</option>\n" +
        "                        <option>蘑菇煲</option>\n" +
        "                        <option>线</option>\n" +
        "                        <option>羽毛</option>\n" +
        "                        <option>火药</option>\n" +
        "                        <option>小麦种子</option>\n" +
        "                        <option>小麦</option>\n" +
        "                        <option>面包</option>\n" +
        "                        <option>燧石</option>\n" +
        "                        <option>生猪排</option>\n" +
        "                        <option>熟猪排</option>\n" +
        "                        <option>画</option>\n" +
        "                        <option>金苹果</option>\n" +
        "                        <option>附魔金苹果</option>\n" +
        "                        <option>桶</option>\n" +
        "                        <option>水桶</option>\n" +
        "                        <option>熔岩桶</option>\n" +
        "                        <option>奶桶</option>\n" +
        "                        <option>矿车</option>\n" +
        "                        <option>鞍</option>\n" +
        "                        <option>红石</option>\n" +
        "                        <option>雪球</option>\n" +
        "                        <option>橡木船</option>\n" +
        "                        <option>云杉木船</option>\n" +
        "                        <option>白桦木船</option>\n" +
        "                        <option>丛林木船</option>\n" +
        "                        <option>金合欢木船</option>\n" +
        "                        <option>深色橡木船</option>\n" +
        "                        <option>红树木船</option>\n" +
        "                        <option>橡木运输船</option>\n" +
        "                        <option>云杉木运输船</option>\n" +
        "                        <option>白桦木运输船</option>\n" +
        "                        <option>丛林木运输船</option>\n" +
        "                        <option>金合欢木运输船</option>\n" +
        "                        <option>深色橡木运输船</option>\n" +
        "                        <option>红树木运输船</option>\n" +
        "                        <option>皮革</option>\n" +
        "                        <option>河豚桶</option>\n" +
        "                        <option>鲑鱼桶</option>\n" +
        "                        <option>鳕鱼桶</option>\n" +
        "                        <option>热带鱼桶</option>\n" +
        "                        <option>红砖</option>\n" +
        "                        <option>黏土</option>\n" +
        "                        <option>甘蔗</option>\n" +
        "                        <option>海带</option>\n" +
        "                        <option>纸</option>\n" +
        "                        <option>书</option>\n" +
        "                        <option>黏液球</option>\n" +
        "                        <option>运输矿车</option>\n" +
        "                        <option>动力矿车</option>\n" +
        "                        <option>TNT矿车</option>\n" +
        "                        <option>漏斗矿车</option>\n" +
        "                        <option>命令方块矿车</option>\n" +
        "                        <option>鸡蛋</option>\n" +
        "                        <option>指南针</option>\n" +
        "                        <option>追溯指针</option>\n" +
        "                        <option>钓鱼竿</option>\n" +
        "                        <option>时钟</option>\n" +
        "                        <option>荧石粉</option>\n" +
        "                        <option>生鳕鱼</option>\n" +
        "                        <option>生鲑鱼</option>\n" +
        "                        <option>热带鱼</option>\n" +
        "                        <option>河豚</option>\n" +
        "                        <option>熟鳕鱼</option>\n" +
        "                        <option>熟鲑鱼</option>\n" +
        "                        <option>蜂蜜瓶</option>\n" +
        "                        <option>蜜脾</option>\n" +
        "                        <option>墨囊</option>\n" +
        "                        <option>红色染料</option>\n" +
        "                        <option>绿色染料</option>\n" +
        "                        <option>可可豆</option>\n" +
        "                        <option>青金石</option>\n" +
        "                        <option>紫色染料</option>\n" +
        "                        <option>青色染料</option>\n" +
        "                        <option>淡灰色染料</option>\n" +
        "                        <option>灰色染料</option>\n" +
        "                        <option>粉红色染料</option>\n" +
        "                        <option>黄绿色染料</option>\n" +
        "                        <option>黄色染料</option>\n" +
        "                        <option>淡蓝色染料</option>\n" +
        "                        <option>品红色染料</option>\n" +
        "                        <option>橙色染料</option>\n" +
        "                        <option>骨粉</option>\n" +
        "                        <option>蓝色染料</option>\n" +
        "                        <option>棕色染料</option>\n" +
        "                        <option>黑色染料</option>\n" +
        "                        <option>白色染料</option>\n" +
        "                        <option>骨头</option>\n" +
        "                        <option>糖</option>\n" +
        "                        <option>曲奇</option>\n" +
        "                        <option>剪刀</option>\n" +
        "                        <option>西瓜片</option>\n" +
        "                        <option>干海带</option>\n" +
        "                        <option>南瓜种子</option>\n" +
        "                        <option>西瓜种</option>\n" +
        "                        <option>生牛肉</option>\n" +
        "                        <option>牛排</option>\n" +
        "                        <option>生鸡肉</option>\n" +
        "                        <option>熟鸡肉</option>\n" +
        "                        <option>腐肉</option>\n" +
        "                        <option>末影珍珠</option>\n" +
        "                        <option>烈焰棒</option>\n" +
        "                        <option>恶魂之泪</option>\n" +
        "                        <option>金粒</option>\n" +
        "                        <option>下界疣</option>\n" +
        "                        <option>玻璃瓶</option>\n" +
        "                        <option>药水</option>\n" +
        "                        <option>喷溅药水</option>\n" +
        "                        <option>滞留药水</option>\n" +
        "                        <option>药箭</option>\n" +
        "                        <option>光灵箭</option>\n" +
        "                        <option>蜘蛛眼</option>\n" +
        "                        <option>发酵蛛眼</option>\n" +
        "                        <option>烈焰粉</option>\n" +
        "                        <option>岩浆膏</option>\n" +
        "                        <option>末影之眼</option>\n" +
        "                        <option>闪烁的西瓜片</option>\n" +
        "                        <option>附魔之瓶</option>\n" +
        "                        <option>火焰弹</option>\n" +
        "                        <option>书与笔</option>\n" +
        "                        <option>成书</option>\n" +
        "                        <option>绿宝石</option>\n" +
        "                        <option>物品展示框</option>\n" +
        "                        <option>胡萝卜</option>\n" +
        "                        <option>马铃薯</option>\n" +
        "                        <option>烤马铃薯</option>\n" +
        "                        <option>毒马铃薯</option>\n" +
        "                        <option>空地图</option>\n" +
        "                        <option>地图或探险家地图</option>\n" +
        "                        <option>金胡萝卜</option>\n" +
        "                        <option>胡萝卜钓竿</option>\n" +
        "                        <option>下界之星</option>\n" +
        "                        <option>南瓜派</option>\n" +
        "                        <option>烟花火箭</option>\n" +
        "                        <option>烟火之星</option>\n" +
        "                        <option>附魔书</option>\n" +
        "                        <option>下界砖</option>\n" +
        "                        <option>下界石英</option>\n" +
        "                        <option>海晶碎片</option>\n" +
        "                        <option>海晶砂粒</option>\n" +
        "                        <option>生兔肉</option>\n" +
        "                        <option>熟兔肉</option>\n" +
        "                        <option>兔肉煲</option>\n" +
        "                        <option>兔子脚</option>\n" +
        "                        <option>兔子皮</option>\n" +
        "                        <option>盔甲架</option>\n" +
        "                        <option>铁马铠</option>\n" +
        "                        <option>金马铠</option>\n" +
        "                        <option>钻石马铠</option>\n" +
        "                        <option>拴绳</option>\n" +
        "                        <option>命名牌</option>\n" +
        "                        <option>生羊肉</option>\n" +
        "                        <option>熟羊肉</option>\n" +
        "                        <option>末地水晶</option>\n" +
        "                        <option>紫颂果</option>\n" +
        "                        <option>爆裂紫颂果</option>\n" +
        "                        <option>甜菜根</option>\n" +
        "                        <option>甜菜种子</option>\n" +
        "                        <option>甜菜汤</option>\n" +
        "                        <option>龙息</option>\n" +
        "                        <option>盾牌</option>\n" +
        "                        <option>鞘翅</option>\n" +
        "                        <option>不死图腾</option>\n" +
        "                        <option>潜影壳</option>\n" +
        "                        <option>铁粒</option>\n" +
        "                        <option>知识之书</option>\n" +
        "                        <option>三叉戟</option>\n" +
        "                        <option>幻翼膜</option>\n" +
        "                        <option>鹦鹉螺壳</option>\n" +
        "                        <option>海洋之心</option>\n" +
        "                        <option>音乐唱片13</option>\n" +
        "                        <option>音乐唱片Cat</option>\n" +
        "                        <option>音乐唱片Blocks</option>\n" +
        "                        <option>音乐唱片Chirp</option>\n" +
        "                        <option>音乐唱片Far</option>\n" +
        "                        <option>音乐唱片Mall</option>\n" +
        "                        <option>音乐唱片Mellohi</option>\n" +
        "                        <option>音乐唱片Stal</option>\n" +
        "                        <option>音乐唱片Strad</option>\n" +
        "                        <option>音乐唱片Ward</option>\n" +
        "                        <option>音乐唱片11</option>\n" +
        "                        <option>音乐唱片Wait</option>\n" +
        "                        <option>调试棒</option>\n" +
        "                        <option>蝙蝠刷怪蛋</option>\n" +
        "                        <option>蜜蜂刷怪蛋</option>\n" +
        "                        <option>烈焰人刷怪蛋</option>\n" +
        "                        <option>猫刷怪蛋</option>\n" +
        "                        <option>洞穴蜘蛛刷怪蛋</option>\n" +
        "                        <option>鸡刷怪蛋</option>\n" +
        "                        <option>鳕鱼刷怪蛋</option>\n" +
        "                        <option>牛刷怪蛋</option>\n" +
        "                        <option>苦力怕刷怪蛋</option>\n" +
        "                        <option>海豚刷怪蛋</option>\n" +
        "                        <option>骡刷怪蛋</option>\n" +
        "                        <option>溺尸刷怪蛋</option>\n" +
        "                        <option>远古守卫者刷怪蛋</option>\n" +
        "                        <option>末影人刷怪蛋</option>\n" +
        "                        <option>末影螨刷怪蛋</option>\n" +
        "                        <option>唤魔者刷怪蛋</option>\n" +
        "                        <option>青蛙刷怪蛋</option>\n" +
        "                        <option>恶魂刷怪蛋</option>\n" +
        "                        <option>守卫者刷怪蛋</option>\n" +
        "                        <option>马刷怪蛋</option>\n" +
        "                        <option>尸壳刷怪蛋</option>\n" +
        "                        <option>劫掠兽刷怪蛋</option>\n" +
        "                        <option>羊驼刷怪蛋</option>\n" +
        "                        <option>岩浆怪刷怪蛋</option>\n" +
        "                        <option>哞菇刷怪蛋</option>\n" +
        "                        <option>骡刷怪蛋</option>\n" +
        "                        <option>豹猫刷怪蛋</option>\n" +
        "                        <option>熊猫刷怪蛋</option>\n" +
        "                        <option>鹦鹉刷怪蛋</option>\n" +
        "                        <option>幻翼刷怪蛋</option>\n" +
        "                        <option>猪刷怪蛋</option>\n" +
        "                        <option>掠夺者刷怪蛋</option>\n" +
        "                        <option>北极熊刷怪蛋</option>\n" +
        "                        <option>河豚刷怪蛋</option>\n" +
        "                        <option>兔子刷怪蛋</option>\n" +
        "                        <option>鲑鱼刷怪蛋</option>\n" +
        "                        <option>绵羊刷怪蛋</option>\n" +
        "                        <option>潜影贝刷怪蛋</option>\n" +
        "                        <option>蠹虫刷怪蛋</option>\n" +
        "                        <option>骷髅刷怪蛋</option>\n" +
        "                        <option>骷髅马刷怪蛋</option>\n" +
        "                        <option>史莱姆刷怪蛋</option>\n" +
        "                        <option>蜘蛛刷怪蛋</option>\n" +
        "                        <option>鱿鱼刷怪蛋</option>\n" +
        "                        <option>流浪者刷怪蛋</option>\n" +
        "                        <option>蝌蚪刷怪蛋</option>\n" +
        "                        <option>热带鱼刷怪蛋</option>\n" +
        "                        <option>海龟刷怪蛋</option>\n" +
        "                        <option>恼鬼刷怪蛋</option>\n" +
        "                        <option>村民刷怪蛋</option>\n" +
        "                        <option>卫道士刷怪蛋</option>\n" +
        "                        <option>监守者刷怪蛋</option>\n" +
        "                        <option>女巫刷怪蛋</option>\n" +
        "                        <option>凋灵骷髅刷怪蛋</option>\n" +
        "                        <option>狼刷怪蛋</option>\n" +
        "                        <option>僵尸刷怪蛋</option>\n" +
        "                        <option>僵尸马刷怪蛋</option>\n" +
        "                        <option>僵尸猪人刷怪蛋</option>\n" +
        "                        <option>僵尸村民刷怪蛋</option>\n" +
        "                        <option>弩</option>\n" +
        "                        <option>旗帜图案（花盾徽）</option>\n" +
        "                        <option>旗帜图案（苦力怕盾徽）</option>\n" +
        "                        <option>旗帜图案（头颅盾徽）</option>\n" +
        "                        <option>旗帜图案（Mojang盾徽）</option>\n" +
        "                        <option>迷之炖菜</option>\n" +
        "                        <option>回响碎片</option>\n" +
        "                    </select>\n" +
        "                    <p>方块请手动输入(不填默认为选择的)：</p>\n" +
        "                    <input type=\"text\" id=\"buyItems\">\n" +
        "                    <p>买入的物品数量：</p>\n" +
        "                    <input type=\"number\" id=\"buyCount\">\n" +
        "                    <p>&nbsp;</p>\n" +
        "                    <br><button value=\"false\" id=\"disabledBuyB\" style=\"background: #ff4545;border: none;width: auto;height: 25px\" onclick=\"canalBuyBItem(this)\">取消该参数</button>\n" +
        "                    <div id=\"buyBDisabled\">\n" +
        "                        <p>买入的物品2：</p>\n" +
        "                        <select id=\"buyB\">\n" +
        "                            <option>铁剑</option>\n" +
        "                            <option>铁锹</option>\n" +
        "                            <option>铁镐</option>\n" +
        "                            <option>铁斧</option>\n" +
        "                            <option>铁锄</option>\n" +
        "                            <option>木剑</option>\n" +
        "                            <option>木锹</option>\n" +
        "                            <option>木镐</option>\n" +
        "                            <option>木斧</option>\n" +
        "                            <option>木锄</option>\n" +
        "                            <option>石剑</option>\n" +
        "                            <option>石锹</option>\n" +
        "                            <option>石镐</option>\n" +
        "                            <option>石斧</option>\n" +
        "                            <option>石锄</option>\n" +
        "                            <option>钻石剑</option>\n" +
        "                            <option>钻石锹</option>\n" +
        "                            <option>钻石镐</option>\n" +
        "                            <option>钻石斧</option>\n" +
        "                            <option>钻石锄</option>\n" +
        "                            <option>金剑</option>\n" +
        "                            <option>金锹</option>\n" +
        "                            <option>金镐</option>\n" +
        "                            <option>金斧</option>\n" +
        "                            <option>金锄</option>\n" +
        "                            <option>皮革头盔</option>\n" +
        "                            <option>皮革胸甲</option>\n" +
        "                            <option>皮革护腿</option>\n" +
        "                            <option>皮革靴子</option>\n" +
        "                            <option>锁链头盔</option>\n" +
        "                            <option>锁链胸甲</option>\n" +
        "                            <option>锁链护腿</option>\n" +
        "                            <option>锁链靴子</option>\n" +
        "                            <option>铁头盔</option>\n" +
        "                            <option>铁胸甲</option>\n" +
        "                            <option>铁护腿</option>\n" +
        "                            <option>铁靴子</option>\n" +
        "                            <option>钻石头盔</option>\n" +
        "                            <option>钻石胸甲</option>\n" +
        "                            <option>钻石护腿</option>\n" +
        "                            <option>钻石靴子</option>\n" +
        "                            <option>金头盔</option>\n" +
        "                            <option>金胸甲</option>\n" +
        "                            <option>金护腿</option>\n" +
        "                            <option>金靴子</option>\n" +
        "                            <option>海龟壳</option>\n" +
        "                            <option>鳞甲</option>\n" +
        "                            <option>打火石</option>\n" +
        "                            <option>弓</option>\n" +
        "                            <option>箭</option>\n" +
        "                            <option>苹果</option>\n" +
        "                            <option>煤炭</option>\n" +
        "                            <option>木炭</option>\n" +
        "                            <option>钻石</option>\n" +
        "                            <option>铁锭</option>\n" +
        "                            <option>金锭</option>\n" +
        "                            <option>木棍</option>\n" +
        "                            <option>碗</option>\n" +
        "                            <option>蘑菇煲</option>\n" +
        "                            <option>线</option>\n" +
        "                            <option>羽毛</option>\n" +
        "                            <option>火药</option>\n" +
        "                            <option>小麦种子</option>\n" +
        "                            <option>小麦</option>\n" +
        "                            <option>面包</option>\n" +
        "                            <option>燧石</option>\n" +
        "                            <option>生猪排</option>\n" +
        "                            <option>熟猪排</option>\n" +
        "                            <option>画</option>\n" +
        "                            <option>金苹果</option>\n" +
        "                            <option>附魔金苹果</option>\n" +
        "                            <option>桶</option>\n" +
        "                            <option>水桶</option>\n" +
        "                            <option>熔岩桶</option>\n" +
        "                            <option>奶桶</option>\n" +
        "                            <option>矿车</option>\n" +
        "                            <option>鞍</option>\n" +
        "                            <option>红石</option>\n" +
        "                            <option>雪球</option>\n" +
        "                            <option>橡木船</option>\n" +
        "                            <option>云杉木船</option>\n" +
        "                            <option>白桦木船</option>\n" +
        "                            <option>丛林木船</option>\n" +
        "                            <option>金合欢木船</option>\n" +
        "                            <option>深色橡木船</option>\n" +
        "                            <option>红树木船</option>\n" +
        "                            <option>橡木运输船</option>\n" +
        "                            <option>云杉木运输船</option>\n" +
        "                            <option>白桦木运输船</option>\n" +
        "                            <option>丛林木运输船</option>\n" +
        "                            <option>金合欢木运输船</option>\n" +
        "                            <option>深色橡木运输船</option>\n" +
        "                            <option>红树木运输船</option>\n" +
        "                            <option>皮革</option>\n" +
        "                            <option>河豚桶</option>\n" +
        "                            <option>鲑鱼桶</option>\n" +
        "                            <option>鳕鱼桶</option>\n" +
        "                            <option>热带鱼桶</option>\n" +
        "                            <option>红砖</option>\n" +
        "                            <option>黏土</option>\n" +
        "                            <option>甘蔗</option>\n" +
        "                            <option>海带</option>\n" +
        "                            <option>纸</option>\n" +
        "                            <option>书</option>\n" +
        "                            <option>黏液球</option>\n" +
        "                            <option>运输矿车</option>\n" +
        "                            <option>动力矿车</option>\n" +
        "                            <option>TNT矿车</option>\n" +
        "                            <option>漏斗矿车</option>\n" +
        "                            <option>命令方块矿车</option>\n" +
        "                            <option>鸡蛋</option>\n" +
        "                            <option>指南针</option>\n" +
        "                            <option>追溯指针</option>\n" +
        "                            <option>钓鱼竿</option>\n" +
        "                            <option>时钟</option>\n" +
        "                            <option>荧石粉</option>\n" +
        "                            <option>生鳕鱼</option>\n" +
        "                            <option>生鲑鱼</option>\n" +
        "                            <option>热带鱼</option>\n" +
        "                            <option>河豚</option>\n" +
        "                            <option>熟鳕鱼</option>\n" +
        "                            <option>熟鲑鱼</option>\n" +
        "                            <option>蜂蜜瓶</option>\n" +
        "                            <option>蜜脾</option>\n" +
        "                            <option>墨囊</option>\n" +
        "                            <option>红色染料</option>\n" +
        "                            <option>绿色染料</option>\n" +
        "                            <option>可可豆</option>\n" +
        "                            <option>青金石</option>\n" +
        "                            <option>紫色染料</option>\n" +
        "                            <option>青色染料</option>\n" +
        "                            <option>淡灰色染料</option>\n" +
        "                            <option>灰色染料</option>\n" +
        "                            <option>粉红色染料</option>\n" +
        "                            <option>黄绿色染料</option>\n" +
        "                            <option>黄色染料</option>\n" +
        "                            <option>淡蓝色染料</option>\n" +
        "                            <option>品红色染料</option>\n" +
        "                            <option>橙色染料</option>\n" +
        "                            <option>骨粉</option>\n" +
        "                            <option>蓝色染料</option>\n" +
        "                            <option>棕色染料</option>\n" +
        "                            <option>黑色染料</option>\n" +
        "                            <option>白色染料</option>\n" +
        "                            <option>骨头</option>\n" +
        "                            <option>糖</option>\n" +
        "                            <option>曲奇</option>\n" +
        "                            <option>剪刀</option>\n" +
        "                            <option>西瓜片</option>\n" +
        "                            <option>干海带</option>\n" +
        "                            <option>南瓜种子</option>\n" +
        "                            <option>西瓜种</option>\n" +
        "                            <option>生牛肉</option>\n" +
        "                            <option>牛排</option>\n" +
        "                            <option>生鸡肉</option>\n" +
        "                            <option>熟鸡肉</option>\n" +
        "                            <option>腐肉</option>\n" +
        "                            <option>末影珍珠</option>\n" +
        "                            <option>烈焰棒</option>\n" +
        "                            <option>恶魂之泪</option>\n" +
        "                            <option>金粒</option>\n" +
        "                            <option>下界疣</option>\n" +
        "                            <option>玻璃瓶</option>\n" +
        "                            <option>药水</option>\n" +
        "                            <option>喷溅药水</option>\n" +
        "                            <option>滞留药水</option>\n" +
        "                            <option>药箭</option>\n" +
        "                            <option>光灵箭</option>\n" +
        "                            <option>蜘蛛眼</option>\n" +
        "                            <option>发酵蛛眼</option>\n" +
        "                            <option>烈焰粉</option>\n" +
        "                            <option>岩浆膏</option>\n" +
        "                            <option>末影之眼</option>\n" +
        "                            <option>闪烁的西瓜片</option>\n" +
        "                            <option>附魔之瓶</option>\n" +
        "                            <option>火焰弹</option>\n" +
        "                            <option>书与笔</option>\n" +
        "                            <option>成书</option>\n" +
        "                            <option>绿宝石</option>\n" +
        "                            <option>物品展示框</option>\n" +
        "                            <option>胡萝卜</option>\n" +
        "                            <option>马铃薯</option>\n" +
        "                            <option>烤马铃薯</option>\n" +
        "                            <option>毒马铃薯</option>\n" +
        "                            <option>空地图</option>\n" +
        "                            <option>地图或探险家地图</option>\n" +
        "                            <option>金胡萝卜</option>\n" +
        "                            <option>胡萝卜钓竿</option>\n" +
        "                            <option>下界之星</option>\n" +
        "                            <option>南瓜派</option>\n" +
        "                            <option>烟花火箭</option>\n" +
        "                            <option>烟火之星</option>\n" +
        "                            <option>附魔书</option>\n" +
        "                            <option>下界砖</option>\n" +
        "                            <option>下界石英</option>\n" +
        "                            <option>海晶碎片</option>\n" +
        "                            <option>海晶砂粒</option>\n" +
        "                            <option>生兔肉</option>\n" +
        "                            <option>熟兔肉</option>\n" +
        "                            <option>兔肉煲</option>\n" +
        "                            <option>兔子脚</option>\n" +
        "                            <option>兔子皮</option>\n" +
        "                            <option>盔甲架</option>\n" +
        "                            <option>铁马铠</option>\n" +
        "                            <option>金马铠</option>\n" +
        "                            <option>钻石马铠</option>\n" +
        "                            <option>拴绳</option>\n" +
        "                            <option>命名牌</option>\n" +
        "                            <option>生羊肉</option>\n" +
        "                            <option>熟羊肉</option>\n" +
        "                            <option>末地水晶</option>\n" +
        "                            <option>紫颂果</option>\n" +
        "                            <option>爆裂紫颂果</option>\n" +
        "                            <option>甜菜根</option>\n" +
        "                            <option>甜菜种子</option>\n" +
        "                            <option>甜菜汤</option>\n" +
        "                            <option>龙息</option>\n" +
        "                            <option>盾牌</option>\n" +
        "                            <option>鞘翅</option>\n" +
        "                            <option>不死图腾</option>\n" +
        "                            <option>潜影壳</option>\n" +
        "                            <option>铁粒</option>\n" +
        "                            <option>知识之书</option>\n" +
        "                            <option>三叉戟</option>\n" +
        "                            <option>幻翼膜</option>\n" +
        "                            <option>鹦鹉螺壳</option>\n" +
        "                            <option>海洋之心</option>\n" +
        "                            <option>音乐唱片13</option>\n" +
        "                            <option>音乐唱片Cat</option>\n" +
        "                            <option>音乐唱片Blocks</option>\n" +
        "                            <option>音乐唱片Chirp</option>\n" +
        "                            <option>音乐唱片Far</option>\n" +
        "                            <option>音乐唱片Mall</option>\n" +
        "                            <option>音乐唱片Mellohi</option>\n" +
        "                            <option>音乐唱片Stal</option>\n" +
        "                            <option>音乐唱片Strad</option>\n" +
        "                            <option>音乐唱片Ward</option>\n" +
        "                            <option>音乐唱片11</option>\n" +
        "                            <option>音乐唱片Wait</option>\n" +
        "                            <option>调试棒</option>\n" +
        "                            <option>蝙蝠刷怪蛋</option>\n" +
        "                            <option>蜜蜂刷怪蛋</option>\n" +
        "                            <option>烈焰人刷怪蛋</option>\n" +
        "                            <option>猫刷怪蛋</option>\n" +
        "                            <option>洞穴蜘蛛刷怪蛋</option>\n" +
        "                            <option>鸡刷怪蛋</option>\n" +
        "                            <option>鳕鱼刷怪蛋</option>\n" +
        "                            <option>牛刷怪蛋</option>\n" +
        "                            <option>苦力怕刷怪蛋</option>\n" +
        "                            <option>海豚刷怪蛋</option>\n" +
        "                            <option>骡刷怪蛋</option>\n" +
        "                            <option>溺尸刷怪蛋</option>\n" +
        "                            <option>远古守卫者刷怪蛋</option>\n" +
        "                            <option>末影人刷怪蛋</option>\n" +
        "                            <option>末影螨刷怪蛋</option>\n" +
        "                            <option>唤魔者刷怪蛋</option>\n" +
        "                            <option>青蛙刷怪蛋</option>\n" +
        "                            <option>恶魂刷怪蛋</option>\n" +
        "                            <option>守卫者刷怪蛋</option>\n" +
        "                            <option>马刷怪蛋</option>\n" +
        "                            <option>尸壳刷怪蛋</option>\n" +
        "                            <option>劫掠兽刷怪蛋</option>\n" +
        "                            <option>羊驼刷怪蛋</option>\n" +
        "                            <option>岩浆怪刷怪蛋</option>\n" +
        "                            <option>哞菇刷怪蛋</option>\n" +
        "                            <option>骡刷怪蛋</option>\n" +
        "                            <option>豹猫刷怪蛋</option>\n" +
        "                            <option>熊猫刷怪蛋</option>\n" +
        "                            <option>鹦鹉刷怪蛋</option>\n" +
        "                            <option>幻翼刷怪蛋</option>\n" +
        "                            <option>猪刷怪蛋</option>\n" +
        "                            <option>掠夺者刷怪蛋</option>\n" +
        "                            <option>北极熊刷怪蛋</option>\n" +
        "                            <option>河豚刷怪蛋</option>\n" +
        "                            <option>兔子刷怪蛋</option>\n" +
        "                            <option>鲑鱼刷怪蛋</option>\n" +
        "                            <option>绵羊刷怪蛋</option>\n" +
        "                            <option>潜影贝刷怪蛋</option>\n" +
        "                            <option>蠹虫刷怪蛋</option>\n" +
        "                            <option>骷髅刷怪蛋</option>\n" +
        "                            <option>骷髅马刷怪蛋</option>\n" +
        "                            <option>史莱姆刷怪蛋</option>\n" +
        "                            <option>蜘蛛刷怪蛋</option>\n" +
        "                            <option>鱿鱼刷怪蛋</option>\n" +
        "                            <option>流浪者刷怪蛋</option>\n" +
        "                            <option>蝌蚪刷怪蛋</option>\n" +
        "                            <option>热带鱼刷怪蛋</option>\n" +
        "                            <option>海龟刷怪蛋</option>\n" +
        "                            <option>恼鬼刷怪蛋</option>\n" +
        "                            <option>村民刷怪蛋</option>\n" +
        "                            <option>卫道士刷怪蛋</option>\n" +
        "                            <option>监守者刷怪蛋</option>\n" +
        "                            <option>女巫刷怪蛋</option>\n" +
        "                            <option>凋灵骷髅刷怪蛋</option>\n" +
        "                            <option>狼刷怪蛋</option>\n" +
        "                            <option>僵尸刷怪蛋</option>\n" +
        "                            <option>僵尸马刷怪蛋</option>\n" +
        "                            <option>僵尸猪人刷怪蛋</option>\n" +
        "                            <option>僵尸村民刷怪蛋</option>\n" +
        "                            <option>弩</option>\n" +
        "                            <option>旗帜图案（花盾徽）</option>\n" +
        "                            <option>旗帜图案（苦力怕盾徽）</option>\n" +
        "                            <option>旗帜图案（头颅盾徽）</option>\n" +
        "                            <option>旗帜图案（Mojang盾徽）</option>\n" +
        "                            <option>迷之炖菜</option>\n" +
        "                            <option>回响碎片</option>\n" +
        "                        </select>\n" +
        "                        <p>方块请手动输入(不填默认为选择的)：</p>\n" +
        "                        <input type=\"text\" id=\"buyBItems2\">\n" +
        "                        <p>买入的物品数量2：</p>\n" +
        "                        <input type=\"number\" id=\"buyBCount2\">\n" +
        "                    </div>\n" +
        "                    <p>卖出的物品</p>\n" +
        "                    <select id=\"sellItem\">\n" +
        "                        <option>铁剑</option>\n" +
        "                        <option>铁锹</option>\n" +
        "                        <option>铁镐</option>\n" +
        "                        <option>铁斧</option>\n" +
        "                        <option>铁锄</option>\n" +
        "                        <option>木剑</option>\n" +
        "                        <option>木锹</option>\n" +
        "                        <option>木镐</option>\n" +
        "                        <option>木斧</option>\n" +
        "                        <option>木锄</option>\n" +
        "                        <option>石剑</option>\n" +
        "                        <option>石锹</option>\n" +
        "                        <option>石镐</option>\n" +
        "                        <option>石斧</option>\n" +
        "                        <option>石锄</option>\n" +
        "                        <option>钻石剑</option>\n" +
        "                        <option>钻石锹</option>\n" +
        "                        <option>钻石镐</option>\n" +
        "                        <option>钻石斧</option>\n" +
        "                        <option>钻石锄</option>\n" +
        "                        <option>金剑</option>\n" +
        "                        <option>金锹</option>\n" +
        "                        <option>金镐</option>\n" +
        "                        <option>金斧</option>\n" +
        "                        <option>金锄</option>\n" +
        "                        <option>皮革头盔</option>\n" +
        "                        <option>皮革胸甲</option>\n" +
        "                        <option>皮革护腿</option>\n" +
        "                        <option>皮革靴子</option>\n" +
        "                        <option>锁链头盔</option>\n" +
        "                        <option>锁链胸甲</option>\n" +
        "                        <option>锁链护腿</option>\n" +
        "                        <option>锁链靴子</option>\n" +
        "                        <option>铁头盔</option>\n" +
        "                        <option>铁胸甲</option>\n" +
        "                        <option>铁护腿</option>\n" +
        "                        <option>铁靴子</option>\n" +
        "                        <option>钻石头盔</option>\n" +
        "                        <option>钻石胸甲</option>\n" +
        "                        <option>钻石护腿</option>\n" +
        "                        <option>钻石靴子</option>\n" +
        "                        <option>金头盔</option>\n" +
        "                        <option>金胸甲</option>\n" +
        "                        <option>金护腿</option>\n" +
        "                        <option>金靴子</option>\n" +
        "                        <option>海龟壳</option>\n" +
        "                        <option>鳞甲</option>\n" +
        "                        <option>打火石</option>\n" +
        "                        <option>弓</option>\n" +
        "                        <option>箭</option>\n" +
        "                        <option>苹果</option>\n" +
        "                        <option>煤炭</option>\n" +
        "                        <option>木炭</option>\n" +
        "                        <option>钻石</option>\n" +
        "                        <option>铁锭</option>\n" +
        "                        <option>金锭</option>\n" +
        "                        <option>木棍</option>\n" +
        "                        <option>碗</option>\n" +
        "                        <option>蘑菇煲</option>\n" +
        "                        <option>线</option>\n" +
        "                        <option>羽毛</option>\n" +
        "                        <option>火药</option>\n" +
        "                        <option>小麦种子</option>\n" +
        "                        <option>小麦</option>\n" +
        "                        <option>面包</option>\n" +
        "                        <option>燧石</option>\n" +
        "                        <option>生猪排</option>\n" +
        "                        <option>熟猪排</option>\n" +
        "                        <option>画</option>\n" +
        "                        <option>金苹果</option>\n" +
        "                        <option>附魔金苹果</option>\n" +
        "                        <option>桶</option>\n" +
        "                        <option>水桶</option>\n" +
        "                        <option>熔岩桶</option>\n" +
        "                        <option>奶桶</option>\n" +
        "                        <option>矿车</option>\n" +
        "                        <option>鞍</option>\n" +
        "                        <option>红石</option>\n" +
        "                        <option>雪球</option>\n" +
        "                        <option>橡木船</option>\n" +
        "                        <option>云杉木船</option>\n" +
        "                        <option>白桦木船</option>\n" +
        "                        <option>丛林木船</option>\n" +
        "                        <option>金合欢木船</option>\n" +
        "                        <option>深色橡木船</option>\n" +
        "                        <option>红树木船</option>\n" +
        "                        <option>橡木运输船</option>\n" +
        "                        <option>云杉木运输船</option>\n" +
        "                        <option>白桦木运输船</option>\n" +
        "                        <option>丛林木运输船</option>\n" +
        "                        <option>金合欢木运输船</option>\n" +
        "                        <option>深色橡木运输船</option>\n" +
        "                        <option>红树木运输船</option>\n" +
        "                        <option>皮革</option>\n" +
        "                        <option>河豚桶</option>\n" +
        "                        <option>鲑鱼桶</option>\n" +
        "                        <option>鳕鱼桶</option>\n" +
        "                        <option>热带鱼桶</option>\n" +
        "                        <option>红砖</option>\n" +
        "                        <option>黏土</option>\n" +
        "                        <option>甘蔗</option>\n" +
        "                        <option>海带</option>\n" +
        "                        <option>纸</option>\n" +
        "                        <option>书</option>\n" +
        "                        <option>黏液球</option>\n" +
        "                        <option>运输矿车</option>\n" +
        "                        <option>动力矿车</option>\n" +
        "                        <option>TNT矿车</option>\n" +
        "                        <option>漏斗矿车</option>\n" +
        "                        <option>命令方块矿车</option>\n" +
        "                        <option>鸡蛋</option>\n" +
        "                        <option>指南针</option>\n" +
        "                        <option>追溯指针</option>\n" +
        "                        <option>钓鱼竿</option>\n" +
        "                        <option>时钟</option>\n" +
        "                        <option>荧石粉</option>\n" +
        "                        <option>生鳕鱼</option>\n" +
        "                        <option>生鲑鱼</option>\n" +
        "                        <option>热带鱼</option>\n" +
        "                        <option>河豚</option>\n" +
        "                        <option>熟鳕鱼</option>\n" +
        "                        <option>熟鲑鱼</option>\n" +
        "                        <option>蜂蜜瓶</option>\n" +
        "                        <option>蜜脾</option>\n" +
        "                        <option>墨囊</option>\n" +
        "                        <option>红色染料</option>\n" +
        "                        <option>绿色染料</option>\n" +
        "                        <option>可可豆</option>\n" +
        "                        <option>青金石</option>\n" +
        "                        <option>紫色染料</option>\n" +
        "                        <option>青色染料</option>\n" +
        "                        <option>淡灰色染料</option>\n" +
        "                        <option>灰色染料</option>\n" +
        "                        <option>粉红色染料</option>\n" +
        "                        <option>黄绿色染料</option>\n" +
        "                        <option>黄色染料</option>\n" +
        "                        <option>淡蓝色染料</option>\n" +
        "                        <option>品红色染料</option>\n" +
        "                        <option>橙色染料</option>\n" +
        "                        <option>骨粉</option>\n" +
        "                        <option>蓝色染料</option>\n" +
        "                        <option>棕色染料</option>\n" +
        "                        <option>黑色染料</option>\n" +
        "                        <option>白色染料</option>\n" +
        "                        <option>骨头</option>\n" +
        "                        <option>糖</option>\n" +
        "                        <option>曲奇</option>\n" +
        "                        <option>剪刀</option>\n" +
        "                        <option>西瓜片</option>\n" +
        "                        <option>干海带</option>\n" +
        "                        <option>南瓜种子</option>\n" +
        "                        <option>西瓜种</option>\n" +
        "                        <option>生牛肉</option>\n" +
        "                        <option>牛排</option>\n" +
        "                        <option>生鸡肉</option>\n" +
        "                        <option>熟鸡肉</option>\n" +
        "                        <option>腐肉</option>\n" +
        "                        <option>末影珍珠</option>\n" +
        "                        <option>烈焰棒</option>\n" +
        "                        <option>恶魂之泪</option>\n" +
        "                        <option>金粒</option>\n" +
        "                        <option>下界疣</option>\n" +
        "                        <option>玻璃瓶</option>\n" +
        "                        <option>药水</option>\n" +
        "                        <option>喷溅药水</option>\n" +
        "                        <option>滞留药水</option>\n" +
        "                        <option>药箭</option>\n" +
        "                        <option>光灵箭</option>\n" +
        "                        <option>蜘蛛眼</option>\n" +
        "                        <option>发酵蛛眼</option>\n" +
        "                        <option>烈焰粉</option>\n" +
        "                        <option>岩浆膏</option>\n" +
        "                        <option>末影之眼</option>\n" +
        "                        <option>闪烁的西瓜片</option>\n" +
        "                        <option>附魔之瓶</option>\n" +
        "                        <option>火焰弹</option>\n" +
        "                        <option>书与笔</option>\n" +
        "                        <option>成书</option>\n" +
        "                        <option>绿宝石</option>\n" +
        "                        <option>物品展示框</option>\n" +
        "                        <option>胡萝卜</option>\n" +
        "                        <option>马铃薯</option>\n" +
        "                        <option>烤马铃薯</option>\n" +
        "                        <option>毒马铃薯</option>\n" +
        "                        <option>空地图</option>\n" +
        "                        <option>地图或探险家地图</option>\n" +
        "                        <option>金胡萝卜</option>\n" +
        "                        <option>胡萝卜钓竿</option>\n" +
        "                        <option>下界之星</option>\n" +
        "                        <option>南瓜派</option>\n" +
        "                        <option>烟花火箭</option>\n" +
        "                        <option>烟火之星</option>\n" +
        "                        <option>附魔书</option>\n" +
        "                        <option>下界砖</option>\n" +
        "                        <option>下界石英</option>\n" +
        "                        <option>海晶碎片</option>\n" +
        "                        <option>海晶砂粒</option>\n" +
        "                        <option>生兔肉</option>\n" +
        "                        <option>熟兔肉</option>\n" +
        "                        <option>兔肉煲</option>\n" +
        "                        <option>兔子脚</option>\n" +
        "                        <option>兔子皮</option>\n" +
        "                        <option>盔甲架</option>\n" +
        "                        <option>铁马铠</option>\n" +
        "                        <option>金马铠</option>\n" +
        "                        <option>钻石马铠</option>\n" +
        "                        <option>拴绳</option>\n" +
        "                        <option>命名牌</option>\n" +
        "                        <option>生羊肉</option>\n" +
        "                        <option>熟羊肉</option>\n" +
        "                        <option>末地水晶</option>\n" +
        "                        <option>紫颂果</option>\n" +
        "                        <option>爆裂紫颂果</option>\n" +
        "                        <option>甜菜根</option>\n" +
        "                        <option>甜菜种子</option>\n" +
        "                        <option>甜菜汤</option>\n" +
        "                        <option>龙息</option>\n" +
        "                        <option>盾牌</option>\n" +
        "                        <option>鞘翅</option>\n" +
        "                        <option>不死图腾</option>\n" +
        "                        <option>潜影壳</option>\n" +
        "                        <option>铁粒</option>\n" +
        "                        <option>知识之书</option>\n" +
        "                        <option>三叉戟</option>\n" +
        "                        <option>幻翼膜</option>\n" +
        "                        <option>鹦鹉螺壳</option>\n" +
        "                        <option>海洋之心</option>\n" +
        "                        <option>音乐唱片13</option>\n" +
        "                        <option>音乐唱片Cat</option>\n" +
        "                        <option>音乐唱片Blocks</option>\n" +
        "                        <option>音乐唱片Chirp</option>\n" +
        "                        <option>音乐唱片Far</option>\n" +
        "                        <option>音乐唱片Mall</option>\n" +
        "                        <option>音乐唱片Mellohi</option>\n" +
        "                        <option>音乐唱片Stal</option>\n" +
        "                        <option>音乐唱片Strad</option>\n" +
        "                        <option>音乐唱片Ward</option>\n" +
        "                        <option>音乐唱片11</option>\n" +
        "                        <option>音乐唱片Wait</option>\n" +
        "                        <option>调试棒</option>\n" +
        "                        <option>蝙蝠刷怪蛋</option>\n" +
        "                        <option>蜜蜂刷怪蛋</option>\n" +
        "                        <option>烈焰人刷怪蛋</option>\n" +
        "                        <option>猫刷怪蛋</option>\n" +
        "                        <option>洞穴蜘蛛刷怪蛋</option>\n" +
        "                        <option>鸡刷怪蛋</option>\n" +
        "                        <option>鳕鱼刷怪蛋</option>\n" +
        "                        <option>牛刷怪蛋</option>\n" +
        "                        <option>苦力怕刷怪蛋</option>\n" +
        "                        <option>海豚刷怪蛋</option>\n" +
        "                        <option>骡刷怪蛋</option>\n" +
        "                        <option>溺尸刷怪蛋</option>\n" +
        "                        <option>远古守卫者刷怪蛋</option>\n" +
        "                        <option>末影人刷怪蛋</option>\n" +
        "                        <option>末影螨刷怪蛋</option>\n" +
        "                        <option>唤魔者刷怪蛋</option>\n" +
        "                        <option>青蛙刷怪蛋</option>\n" +
        "                        <option>恶魂刷怪蛋</option>\n" +
        "                        <option>守卫者刷怪蛋</option>\n" +
        "                        <option>马刷怪蛋</option>\n" +
        "                        <option>尸壳刷怪蛋</option>\n" +
        "                        <option>劫掠兽刷怪蛋</option>\n" +
        "                        <option>羊驼刷怪蛋</option>\n" +
        "                        <option>岩浆怪刷怪蛋</option>\n" +
        "                        <option>哞菇刷怪蛋</option>\n" +
        "                        <option>骡刷怪蛋</option>\n" +
        "                        <option>豹猫刷怪蛋</option>\n" +
        "                        <option>熊猫刷怪蛋</option>\n" +
        "                        <option>鹦鹉刷怪蛋</option>\n" +
        "                        <option>幻翼刷怪蛋</option>\n" +
        "                        <option>猪刷怪蛋</option>\n" +
        "                        <option>掠夺者刷怪蛋</option>\n" +
        "                        <option>北极熊刷怪蛋</option>\n" +
        "                        <option>河豚刷怪蛋</option>\n" +
        "                        <option>兔子刷怪蛋</option>\n" +
        "                        <option>鲑鱼刷怪蛋</option>\n" +
        "                        <option>绵羊刷怪蛋</option>\n" +
        "                        <option>潜影贝刷怪蛋</option>\n" +
        "                        <option>蠹虫刷怪蛋</option>\n" +
        "                        <option>骷髅刷怪蛋</option>\n" +
        "                        <option>骷髅马刷怪蛋</option>\n" +
        "                        <option>史莱姆刷怪蛋</option>\n" +
        "                        <option>蜘蛛刷怪蛋</option>\n" +
        "                        <option>鱿鱼刷怪蛋</option>\n" +
        "                        <option>流浪者刷怪蛋</option>\n" +
        "                        <option>蝌蚪刷怪蛋</option>\n" +
        "                        <option>热带鱼刷怪蛋</option>\n" +
        "                        <option>海龟刷怪蛋</option>\n" +
        "                        <option>恼鬼刷怪蛋</option>\n" +
        "                        <option>村民刷怪蛋</option>\n" +
        "                        <option>卫道士刷怪蛋</option>\n" +
        "                        <option>监守者刷怪蛋</option>\n" +
        "                        <option>女巫刷怪蛋</option>\n" +
        "                        <option>凋灵骷髅刷怪蛋</option>\n" +
        "                        <option>狼刷怪蛋</option>\n" +
        "                        <option>僵尸刷怪蛋</option>\n" +
        "                        <option>僵尸马刷怪蛋</option>\n" +
        "                        <option>僵尸猪人刷怪蛋</option>\n" +
        "                        <option>僵尸村民刷怪蛋</option>\n" +
        "                        <option>弩</option>\n" +
        "                        <option>旗帜图案（花盾徽）</option>\n" +
        "                        <option>旗帜图案（苦力怕盾徽）</option>\n" +
        "                        <option>旗帜图案（头颅盾徽）</option>\n" +
        "                        <option>旗帜图案（Mojang盾徽）</option>\n" +
        "                        <option>迷之炖菜</option>\n" +
        "                        <option>回响碎片</option>\n" +
        "                    </select>\n" +
        "                    <p>方块请手动输入(不填默认为选择的)：</p>\n" +
        "                    <input type=\"text\" id=\"sellItems\">\n" +
        "                    <p>卖出的物品数量：</p>\n" +
        "                    <input type=\"number\" id=\"sellCount\">\n" +
        "                    <h4>以下选项不填默认为空</h4>\n" +
        "                    <p>在这个交易获得的经验（不填默认为0）：</p>\n" +
        "                    <input type=\"number\" id=\"xp\">\n" +
        "                    <p>村民重新补货后的价格调节：</p>\n" +
        "                    <input type=\"number\" id=\"demand\">\n" +
        "                    <p>添加到第一个收购物品的价格调节：</p>\n" +
        "                    <input type=\"number\" id=\"speical\">\n" +
        "                    <p>当前应用到此交易选项价格的乘数：</p>\n" +
        "                    <input type=\"number\" id=\"multipliter\">\n" +
        "                </label>\n" +
        "            </div>\n" +
        "        </div>\n" +
        "        <br>\n" +
        "    </div>\n" +
        "    <div class=\"confirm\" onclick=\"fnClose()\">\n" +
        "        <span class=\"close-but\">完成</span>\n" +
        "    </div>\n" +
        "    <script type=\"text/javascript\">\n" +
        "        //let modalHeights = document.getElementById('modal').offsetHeight;\n" +
        "        //document.getElementById('modal').style.marginTop=-(modalHeights/2)+\"px\";\n" +
        "\n" +
        "        function fnClose(){\n" +
        "            document.getElementById('modal').setAttribute(\"class\",\"hidden\");\n" +
        "            document.getElementById('body').setAttribute(\"class\",\"body-class\");\n" +
        "            transaction.unshift({\"id\":TransactionItems+1,\"max\":document.getElementById('max').value,\"buy\":document.getElementById('buy').value,\"buyCount\":document.getElementById('buyCount').value,\"buyItems\":document.getElementById('buyItems').value,\"buyBDisabled\":document.getElementById('disabledBuyB').value,\"buyB\":document.getElementById('buyB').value,\"buyBCount\":document.getElementById('buyBCount2').value,\"buyBItems\":document.getElementById('buyBItems2').value,\"sellItem\":document.getElementById('sellItem').value,\"sellItems\":document.getElementById('sellItems').value,\"sellCount\":document.getElementById('sellCount').value,\"xp\":document.getElementById('xp').value,\"demand\":document.getElementById('demand').value,\"speical\":document.getElementById('speical').value,\"multiplier\":document.getElementById('multipliter').value});" +
        "            let l = new Villager2Loads();\n" +
        "            l.addToList();\n" +
        "            TransactionItems = TransactionItems + 1;\n" +
        "            CreatedWindow = false;" +
        "        }\n" +
        "        AlertWindowConstructor(document.getElementById(\"window\"))" +
        "    </script>\n" +
        "</div></div>";

    gossipsText = "";

    constructor() {
    }

    addTranscation() {
        let body = document.getElementById("body");
        if (!CreatedWindow) {
            body.innerHTML = body.innerHTML + this.transactionText;
            CreatedWindow = true;
            AlertWindowConstructor(document.getElementById("window"));
        } else {
            alert("无法创建多个窗口！");
        }
    }

    addToList() {
        let list = document.getElementById("transactionList");
        let item = "<div value=\"" + TransactionItems + "\" id='TransactionBlockID'>" +
            "<p style='display: inline;'>Transaction " + TransactionItems + "</p>" +
            "</div>";
        list.innerHTML = list.innerHTML + item;
    }

    removeAll() {
        transaction = [];
        document.getElementById("transactionList").innerHTML = "";
    }

    data() {
        let text = "[\n";
        for (let i in transaction) {
            if (transaction[i].max === "") {
                transaction[i].max = null;
            }
            if (transaction[i].buyItems === "") {
                transaction[i].buyItems = null;
            }
            if (transaction[i].buyCount === "") {
                transaction[i].buyCount = null;
            }
            if (transaction[i].buyBItems === "") {
                transaction[i].buyBItems = null;
            }
            if (transaction[i].buyBCount === "") {
                transaction[i].buyBCount = null;
            }
            if (transaction[i].sellItems === "") {
                transaction[i].sellItems = null;
            }
            if (transaction[i].sellCount === "") {
                transaction[i].sellCount = null;
            }
            if (transaction[i].xp === "") {
                transaction[i].xp = null;
            }
            if (transaction[i].demand === "") {
                transaction[i].demand = null;
            }
            if (transaction[i].speical === "") {
                transaction[i].speical = null;
            }
            if (transaction[i].multiplier === "") {
                transaction[i].multiplier = null;
            }
            let obj = '{"id":' + transaction[i].max + ',"max":' + transaction[i].max + ',"buy":' + transaction[i].buy + ',"buyCount":' + transaction[i].buyCount + ',"buyItems":' + transaction[i].buyItems + ',"buyBDisabled":' + transaction[i].buyBDisabled + ',"buyB":' + transaction[i].buyB + ',"buyBCount":' + transaction[i].buyBCount + ',"buyBItems":' + transaction[i].buyBItems + ',"sellItem":' + transaction[i].sellItem + ',"sellItems":' + transaction[i].sellItems + ',"sellCount":' + transaction[i].sellCount + ',"xp":' + transaction[i].xp + ',"demand":' + transaction[i].demand + ',"speical":' + transaction[i].sellCount + ',"multiplier":' + transaction[i].multiplier + '}';
            text = text.concat(obj, ",\n");
        }
        text = text.concat("]");
        alert(text);
    }
}